spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studentsproject
    username: admin
    password: 1
  jpa:
    properties:
      hibernate:
        show_format: true
    #        show_sql: true
    #        generate_statistics: true
    hibernate:
      ddl-auto: update


server:
  port: 9090

  servlet:
    multipart:
        max-file-size: 1000MB
        max-request-size: 1000MB

upload:
  folder: root/ProjectFiles
